apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-voice-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-voice-assistant
  template:
    metadata:
      labels:
        app: ai-voice-assistant
    spec:
      containers:
      - name: ai-voice-assistant
        image: dilliramshah4/ai-voice-assistant:gemini-v1  # Your DockerHub image
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: ai-voice-service
spec:
  type: NodePort
  selector:
    app: ai-voice-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007  # Exposes the service on port 30007
